jenkins:
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Job/Build:authenticated"
      - "Job/Cancel:authenticated"
      - "Job/Configure:authenticated"
      - "Job/Create:authenticated"
      - "Job/Read:authenticated"
      - "Job/Workspace:authenticated"
      - "Overall/Administer:admin"
      - "Overall/Read:anonymous"
      - "Overall/Read:authenticated"
  disableRememberMe: false
  primaryView:
    all:
      name: "all"
  systemMessage: |-
    Powered automagically by Groovy and Configuration-as-Code Plugin

    Don't make manual changes, they will be removed on the next ansible run.
  remotingSecurity:
    enabled: true
  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://127.0.0.1"
        serverCertificate: ""
        skipTlsVerify: true
        credentialsId: "Kubernetes Token"
        namespace: "ci"
        jenkinsUrl: "http://127.0.0.1"
        jenkinsTunnel: "127.0.0.1:50000"
        containerCapStr: 10
        maxRequestsPerHostStr: 64
        retentionTimeout: 5
        connectTimeout: 5
        readTimeout: 15

credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          id: "Kubernetes Token"
          secret: "Sample credentials of exampleuser"
          scope: GLOBAL

security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  sSHD:
    port: -1


unclassified:
  location:
    adminAddress: "Mark Maas <mark.maas@schiphol.nl>"
    url: "http://jenkins.local/"
  gitscm:
    globalConfigName: jenkins
    globalConfigEmail: jenkins@domain.local
    createAccountBasedOnEmail: true


jobs:
  - script: >
      folder('admin') {
        displayName('Admin')
        description('Folder Admin jobs')
      }

      job('admin/Seeding') {
        scm {
          git('git://github.com/blangus/jenkins-test.git')
          // This would download the base ansible
        }
        triggers {
            scm('H/15 * * * *')
        }
        steps {
          jobDsl {
            targets('groovy/*.groovy')
          }
        }
      }

      queue('admin/Seeding')
