# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Jenkins image from Dockerfile
        run: |
          docker build -t blangus/jenkinstest:1.0 .

      - name: Run Trivy scanner and fail on HIGH and CRITICAL vulns.
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'blangus/jenkinstest:1.0'
          exit-code: 1
          severity: HIGH,CRITICAL

      - name: Scan secrets in repo.
        uses: edplato/trufflehog-actions-scan@master
